Sludinajumi/Controllers/AdController.cs
using System;
using System.Threading;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Sludinajumi.Api.Models;
using Sludinajumi.Api.Data;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace Sludinajumi.Controllers
{
    public class AdController : Controller
    {

        private readonly SludinajumiContext context;
        private readonly UserManager<ApplicationUser> userManager;
        
        public AdController(SludinajumiContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> New()
        {
            ViewData["Title"] = "Izvietot jaunu sludinājums";
            List<Category> categories = context.Categories.ToList();
            categories.Remove(categories.Where(cat => cat.Id == 1).FirstOrDefault());
            List<Language> languages = context.Languages.ToList();
            ViewBag.languages = languages;
            ViewBag.categories = categories;
            ApplicationUser curUser = await userManager.GetUserAsync(this.User);
            ViewBag.CreatedById = curUser.Id;
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> New(Ad model)
        {
            if (ModelState.IsValid)
            {
                await context.Ads.AddAsync(model);
                await context.SaveChangesAsync();
                var urlTitle = context.Categories.Find(model.CategoryId).UrlTitle;
                return RedirectToAction(nameof(ShowAd), new { Category = urlTitle, AdId = model.Id });
            }

            ViewData["Title"] = "Izvietot jaunu sludinājums";
            List<Category> categories = context.Categories.ToList();
            categories.Remove(categories.Where(cat => cat.Id == 1).FirstOrDefault());
            List<Language> languages = context.Languages.ToList();
            ViewBag.languages = languages;
            ViewBag.categories = categories;

            return View(model);
        }

        [HttpGet("/Categories/{Category}/Edit/{AdId}")]
        public IActionResult Edit(string Category, long AdId)
        {
            Ad model = context.Ads
                .Include(ad => ad.Category)
                .Include(ad => ad.CreatedBy)
                .Where(ad => ad.Id == AdId)
                .FirstOrDefault();

            if (model == null)
                return NotFound();

            ViewBag.categories = context.Categories.ToList();
            ViewBag.languages = context.Languages.ToList();
            return View(model);
        }

        [HttpPost("/Ad/Edit")]
        public async Task<IActionResult> Edit(Ad model)
        {
            if (model != null || ModelState.IsValid)
            {
                Ad ad = context.Ads.Find(model.Id);
                if (ad == null)
                    return NotFound();
                ad = model;
                context.Update(ad);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(ShowAd), new { Category = ad.Category.Title, AdId = ad.Id });
            }
            return View(model); 
        }

        [HttpGet("/Ad/Remove/{AdId}")]
        public async Task<IActionResult> Remove(long AdId)
        {
            Ad ad = await context.Ads.FindAsync(AdId);
            if (ad == null)
                return NotFound();
            context.Ads.Remove(ad);
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(HomeController.Index));
        }


        [HttpGet("/Categories/{Category}/ShowAd/{AdId}")]
        public async Task<IActionResult> ShowAd(string Category, long AdId)
        {
            Ad model = context.Ads
                .Include(ad => ad.Category)
                .Include(ad => ad.CreatedBy)
                .Where(ad => ad.Id == AdId)
                .FirstOrDefault();
            if (model == null)
                return NotFound();
            
            var relatedAds = context.Ads.Include(ad => ad.Category).Where(ad => 
                (ad.CreatedAt.Ticks > DateTime.Now.AddDays(-1).Ticks &&
                ad.CreatedAt.Ticks < DateTime.Now.Ticks &&
                ad.Category.UrlTitle == Category)).ToList();
            ViewBag.relatedAds = relatedAds;
            ViewBag.relatedCount = relatedAds.Count();

            return View(model);
        }

        [HttpGet("/Categories/{UrlTitle}")]
        public async Task<IActionResult> ShowCategory(string UrlTitle)
        {
            Category category = await context.Categories.Include(cat => cat.Ads)
                .Include(cat => cat.Subcategories)
                .Where(cat => cat.UrlTitle == UrlTitle)
                .SingleOrDefaultAsync();
            return View(category);
        }

    }
}

Sludinajumi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html style="min-height: 100vh !important">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Sludinājumu portāls - @ViewData["Title"]</title>
        <link rel="stylesheet" type="text/css" href="/styles/w3.css" />
        <link rel="stylesheet" type="text/css" href="/styles/main.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-indigo.css">
    </head>
    <body style="min-height: 100vh !important">
        <header class="w3-row w3-padding w3-theme-d2 w3-xlarge">

            <div class="w3-quarter">
                <div class="w3-bar">
                    <a class="w3-bar-item w3-button" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home"></i></a>
                    <span class="w3-bar-item" style="color: white">Sludinājumi</span>
                </div>
            </div>

            <div class="w3-half">
                <input type="search"
                    placeholder="Es meklēju..."
                    class="w3-white w3-border-0 w3-padding"
                    style="width:100%">
            </div>

            <div class="w3-quarter">
                <div class="w3-bar w3-xlarge">
                    <a href="#" class="w3-bar-item w3-button w3-left"><i class="fa fa-search"></i></a>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </header>

        <nav class="w3-bar w3-theme">
            <a asp-area="" asp-controller="Ad" asp-action="New" class="w3-bar-item w3-button w3-hover-green">Jauns sludinājums</a>
            <a href="/swagger/" class="w3-bar-item w3-button w3-hover-green">API dokumentācija</a>
            <a asp-area="" asp-controller="Home" asp-action="About" class="w3-bar-item w3-button w3-hover-green">Par projektu</a>
            <a asp-controller="Home" asp-action="Contacts" class="w3-bar-item w3-button w3-hover-green">Kontakti</a>
        </nav>
        
        <main class="w3-container">
            @RenderBody()
        </main>

        <!-- <footer class="w3-container w3-theme-d3 w3-center">
            <blockquote>
            <p>
                <span class="w3-xxlarge">&#10077;</span>
                <br />
                <i class="w3-large">"Make it as simple as possible, but not simpler."</i>
            </p>
            <p>Albert Einstein</p>
            </blockquote>
        </footer> -->

    </body>
</html>